[Appearance]
style=Fusion
custom_palette=true
color_scheme_path=@HOME@/.config/qt6ct/colors/VioletNight.conf
icon_theme=breeze-dark
standard_dialogs=default
[Fonts]
fixed="JetBrainsMono Nerd Font,11,-1,5,50,0,0,0,0,0"
general="Noto Sans,10,-1,5,50,0,0,0,0,0"
