general {
    hide_cursor = true
}
background {
    monitor =
    path = ~/.local/share/backgrounds/current-wallpaper.webp
    color = rgba(171020ff)
    blur_passes = 2
}
label {
    monitor =
    text = $TIME
    color = rgba(ede3f5ff)
    font_size = 96
    font_family = JetBrainsMono Nerd Font
    position = 0, 160
    halign = center
    valign = center
}
label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgba(b4a3c4ff)
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 60
    halign = center
    valign = center
}
input-field {
    monitor =
    size = 340, 58
    outline_thickness = 2
    rounding = 16
    outer_color = rgba(cf5affff) rgba(a69bffff) 45deg
    inner_color = rgba(241a30ff)
    font_color = rgba(ede3f5ff)
    check_color = rgba(a8cfa0ff)
    fail_color = rgba(ff799dff)
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <i>Password to unlock</i>
    fail_text = $PAMFAIL
    fade_on_empty = false
    dots_spacing = 0.3
    position = 0, -50
    halign = center
    valign = center
}
label {
    monitor =
    text = V I O L E T   N I G H T  ·  $USER
    color = rgba(cf5affff)
    font_size = 13
    font_family = JetBrainsMono Nerd Font
    position = 0, 50
    halign = center
    valign = bottom
}
